language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: python -m unittest discover
notifications:
  slack:
    secure: GxiRsuTT6+vNZOh4kB+D5aqzWQDzM7AYIxcfbAP2dcLEvi52quYJNTCHpg60bYn1bO4rSMgxS9cKSoCcKgmfEp7hwwiXAQbIXrXoMv/GU43o/LFFlaIN0LWO06aHXiqac+5nGScW6OXw/11BVHT5YH391/INAqF5Ge14OjsR7DrlLpx797V4CVP3xEgcp04DMi/U0HLHrwZ3A2ZtC6EAkyBzNMb9CoslSkphOZxp4uo9V3dj+3YwtjWfD3KrHCHm6VZzCVP2T4t9Xgmoi9jGM2l/v7wUlGMYstw74HCURs8RdGJgTw9Y5J4i7XJNwKZHIYsJEF4uvsuKXw65o33WEKYV0RGlQ6cVo/kI6dBzRkxr/llvD6foFdZ9I6kZ6SkUn4VwnpDHIATSZLLVHGXkZUjPDLwLfEjFQOhFR9KaLTQXFADsSYRtgdAFvjZit0qkjgvKzxxn7PTdDN69vs99WbrV1yrF35HW2Sc4YtTvH5mGWRPg5Zq/vuu9/OwYEGR6TcoOXMAN5zsX02VnAhepdOyQNEKP4GzgVh8EeB/mM1c9GG17DlPWKi0/92B4ZBhOAUO/kh90BGkhTDnNxJfv5z+46A+Csesqgq3cd3QZBhtk7UlntVk6NAq9biSqE2jnSmY0PrPOmLCZcPPeY994fpNWJJAZE59BoY5MfW1XmC8=
